# Generated by Django 5.2.8 on 2025-11-25 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_geminisettings_delete_aisettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='integrations.geminisettings')),
            ],
        ),
    ]
