# Generated by Django 5.2.8 on 2025-11-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_brand_name', models.CharField(max_length=255, unique=True, verbose_name='XML Marka Adı')),
                ('trendyol_brand_id', models.IntegerField(verbose_name='Trendyol Marka ID')),
            ],
            options={
                'verbose_name': 'Marka Eşleştirmesi',
                'verbose_name_plural': 'Marka Eşleştirmeleri',
            },
        ),
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_category_name', models.CharField(max_length=500, unique=True, verbose_name='XML Kategori Adı')),
                ('trendyol_category_id', models.IntegerField(verbose_name='Trendyol Kategori ID')),
            ],
            options={
                'verbose_name': 'Kategori Eşleştirmesi',
                'verbose_name_plural': 'Kategori Eşleştirmeleri',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='original_barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Orjinal XML Barkodu'),
        ),
        migrations.AddField(
            model_name='product',
            name='trendyol_brand_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trendyol Marka ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='trendyol_category_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trendyol Kategori ID'),
        ),
    ]
