# Generated by Django 5.2.8 on 2025-11-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categorymapping_trendyol_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Kar Marjı (%)')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kargo/Ek Maliyet (TL)')),
                ('use_unique_barcode', models.BooleanField(default=False, verbose_name='Benzersiz Barkod Oluştur (Eğer yoksa)')),
                ('min_stock', models.IntegerField(default=0, verbose_name='Minimum Stok Limiti (Altındakiler gönderilmez)')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='products.supplier', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Tedarikçi Ayarı',
                'verbose_name_plural': 'Tedarikçi Ayarları',
            },
        ),
    ]
