# Generated by Django 5.2.8 on 2025-11-24 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_suppliersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliersettings',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Varsayılan Kar Marjı (%)'),
        ),
        migrations.AlterField(
            model_name='suppliersettings',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sabit Kargo/Maliyet (TL)'),
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min Fiyat')),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max Fiyat')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Kar Marjı (%)')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sabit Artış (TL)')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='products.supplier', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Fiyat Kuralı',
                'verbose_name_plural': 'Fiyat Kuralları',
                'ordering': ['min_price'],
            },
        ),
    ]
