# Generated by Django 5.2.8 on 2025-11-24 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_pricerule_fixed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ürün Özellikleri (XML)'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Model Kodu (Varyant Grubu)'),
        ),
        migrations.CreateModel(
            name='CategoryAttributeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trendyol_attribute_id', models.IntegerField(verbose_name='Trendyol Özellik ID')),
                ('trendyol_attribute_name', models.CharField(max_length=255, verbose_name='Trendyol Özellik Adı')),
                ('mapping_type', models.CharField(choices=[('fixed', 'Sabit Değer'), ('xml', 'XML Verisinden')], default='fixed', max_length=10, verbose_name='Eşleşme Tipi')),
                ('static_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sabit Değer')),
                ('xml_attribute_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='XML Özellik Adı')),
                ('is_required', models.BooleanField(default=False, verbose_name='Zorunlu mu?')),
                ('is_varianter', models.BooleanField(default=False, verbose_name='Varyant Özelliği mi?')),
                ('is_slicer', models.BooleanField(default=False, verbose_name='Görsel Varyantı mı (Slicer)?')),
                ('category_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_mappings', to='products.categorymapping', verbose_name='Kategori Eşleşmesi')),
            ],
            options={
                'verbose_name': 'Kategori Özellik Eşleşmesi',
                'verbose_name_plural': 'Kategori Özellik Eşleştirmeleri',
            },
        ),
    ]
