# Generated by Django 5.2.8 on 2025-11-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_suppliersettings_default_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersettings',
            name='buying_price_includes_vat',
            field=models.BooleanField(default=True, verbose_name='Alış Fiyatına KDV Dahil'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='buying_vat_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Alış KDV Oranı (%)'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='selling_vat_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Satış KDV Oranı (%)'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=10.19, max_digits=10, verbose_name='Hizmet Bedeli (TL) - KDV Dahil'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='withholding_tax_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Stopaj Oranı (%)'),
        ),
    ]
