# Generated by Django 5.2.8 on 2025-11-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_suppliersettings_auto_sync_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliersettings',
            name='auto_sync_enabled',
        ),
        migrations.RemoveField(
            model_name='suppliersettings',
            name='sync_interval_minutes',
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='auto_update_interval',
            field=models.IntegerField(default=0, verbose_name='Otomatik Güncelleme Aralığı (Dakika)'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='last_auto_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Otomatik Güncelleme'),
        ),
    ]
