# Generated by Django 5.2.8 on 2025-11-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_backgroundprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundprocess',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='İşlem Detayları'),
        ),
    ]
