# Generated by Django 5.2.8 on 2025-11-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_backgroundprocess_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed_images/', verbose_name='İşlenmiş Görsel'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='frame_image',
            field=models.ImageField(blank=True, null=True, upload_to='frames/', verbose_name='Çerçeve Görseli (PNG)'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='use_frame',
            field=models.BooleanField(default=False, verbose_name='Ürün Görsellerine Çerçeve Ekle'),
        ),
    ]
