# Generated by Django 5.2.8 on 2025-11-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productimage_processed_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersettings',
            name='batch_check_interval',
            field=models.IntegerField(default=15, verbose_name='Batch Kontrol Aralığı (Dakika)'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='last_batch_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Batch Kontrolü'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='zero_stock_on_error',
            field=models.BooleanField(default=True, verbose_name='Hata Durumunda Stoğu Sıfırla'),
        ),
    ]
