# Generated by Django 5.2.8 on 2025-11-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_suppliersettings_batch_check_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundprocess',
            name='process_type',
            field=models.CharField(choices=[('xml_sync', 'XML Senkronizasyonu'), ('manual_xml_sync', 'Manuel XML Senkronizasyonu'), ('trendyol_update', 'Trendyol Güncellemesi')], max_length=50, verbose_name='İşlem Tipi'),
        ),
    ]
