# Generated by Django 5.2.8 on 2025-11-26 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_backgroundprocess_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyolbatchrequest',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_requests', to='products.backgroundprocess', verbose_name='İlgili İşlem'),
        ),
    ]
