# Generated by Django 5.2.8 on 2025-11-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_trendyolbatchrequest_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='cloudinary_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Cloudinary URL'),
        ),
    ]
