# Generated by Django 5.2.8 on 2025-11-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productimage_cloudinary_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trendyol_attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Trendyol Özellikleri (AI)'),
        ),
    ]
